[package]
name = "csv_sql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.8"
nom = "7.1.3"
tokio = "1.34.0"
log = "0.4.22"

